name: ocr_kk
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_mlkit_text_recognition: ^0.8.1
  image_picker: ^0.8.2
  flutter: 
    sdk: flutter
  intl: ^0.18.1
  path: ^1.8.3
  gap: ^3.0.1
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  gallery_saver: ^2.3.2
  image: ^4.1.3
  edge_detection: ^1.1.3
  google_fonts: ^4.0.4
  flutter_screenutil: ^5.9.0
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

